DROP TABLE IF EXISTS HOMES CASCADE;
CREATE TABLE HOMES (
    id   SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    street VARCHAR(128) NOT NULL,
    city VARCHAR(128) NOT NULL,
    post_code VARCHAR(128) NOT NULL,
    country VARCHAR(128) NOT NULL
);

DROP TYPE IF EXISTS SENSOR_TYPE CASCADE;
CREATE TYPE SENSOR_TYPE AS ENUM ('TEMPERATURE', 'AIR_POLLUTION', 'AIR_HUMIDITY');
DROP TABLE IF EXISTS SENSORS CASCADE;
CREATE TABLE SENSORS (
    id   SERIAL PRIMARY KEY,
    type SENSOR_TYPE NOT NULL,
    name VARCHAR(128) NOT NULL,
    manufacturer VARCHAR(128) NOT NULL,
    serial_number VARCHAR(128) NOT NULL,
    created_at DATE,
    home_id INT,
    FOREIGN KEY (home_id) REFERENCES HOMES(ID)
);

DROP TYPE IF EXISTS MEASUREMENT_TYPE CASCADE;
CREATE TYPE MEASUREMENT_TYPE AS ENUM ('CELSIUS', '%HUMIDITY', 'IAI', 'PM25', 'GAS');
DROP TABLE IF EXISTS MEASUREMENTS CASCADE;
CREATE TABLE MEASUREMENTS (
    id   SERIAL PRIMARY KEY,
    type MEASUREMENT_TYPE NOT NULL,
    value int NOT NULL,
    created_at DATE,
    sensor_id INT,
    FOREIGN KEY (sensor_id) REFERENCES SENSORS(ID)
);

DROP TYPE IF EXISTS DEVICE_TYPE CASCADE;
CREATE TYPE DEVICE_TYPE AS ENUM ('AIR_FILTER', 'AIR_CONDITIONING', 'AIR_HUMIDIFIER');
DROP TABLE IF EXISTS FUNCTIONAL_DEVICES CASCADE;
CREATE TABLE FUNCTIONAL_DEVICES (
    id   SERIAL PRIMARY KEY,
    type DEVICE_TYPE NOT NULL,
    name VARCHAR(128) NOT NULL,
    manufacturer VARCHAR(128) NOT NULL,
    serial_number VARCHAR(128) NOT NULL,
    consumed_electricity INT NOT NULL,
    created_at DATE,
    home_id INT,
    FOREIGN KEY (home_id) REFERENCES HOMES(ID)
);

DROP TABLE IF EXISTS FUNCTIONAL_DEVICE_CONSUMPTIONS CASCADE;
CREATE TABLE FUNCTIONAL_DEVICE_CONSUMPTIONS (
    id   SERIAL PRIMARY KEY,
    level INT,
    average_consumption_per_hour INT NOT NULL,
    functional_device_id INT NOT NULL,
    FOREIGN KEY (functional_device_id) REFERENCES FUNCTIONAL_DEVICES(ID)
);