name: Air Conditioning

on:
  push:
    paths:
      - "*.gradle"
      - "Air-Filter/**"
      - "Common-Code/**"
  workflow_dispatch:
    inputs:
      version:
        description: Run Manually

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Get gradlew
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the App
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :Air-Conditioning:build -x test
          gradle-executable: gradlew

  test:
    runs-on: ubuntu-latest
    name: Tests
    needs: Build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Get gradlew
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test the App
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :Air-Conditioning:test --scan
          gradle-executable: gradlew

      - name: Save report if error
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./Air-Conditioning/build/reports/tests