name: Data Service

on:
  push:
    paths:
      - "*.gradle"
      - "Control-Service/**"
      - "Common-Code/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the App
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :Control-Service:build -x test
          build-root-directory: .
          gradle-executable: ./gradlew

  test:
    runs-on: ubuntu-latest
    name: Tests
    needs: Build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test the App
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :Control-Service:test --scan
          build-root-directory: .
          gradle-executable: ./gradlew

      - name: Save report if error
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./Control-Service/build/reports/tests